### ISSUE TITLE
notes don't render correctly on dev.realworldocaml.org

### ISSUE THREAD

**Issue by yminsky** [realworldocaml/book#3329]
You can see it here:

   https://dev.realworldocaml.org/guided-tour.html

The section titled "base core and core_kernel"  has an undifferentiated white background, but it should be on a yellow box.

Note that it renders correctly when I build locally and look at it on the browser: the yellow background shows up as expected.  I have no idea why it's messed up only on dev.realworldocaml.org...

**Comment by avsm** [comment]
Something something something css.  Might be due to a cross-domain issue somewhere there.

**Comment by yminsky** [comment]
Can I ping this again? I'd really like to get the rendering issue fixed here.

**Comment by avsm** [comment]
Fixed! https://dev.realworldocaml.org/guided-tour.html

**Comment by yminsky** [comment]
This still doesn't work properly on my local build. Any idea why?

**Comment by avsm** [comment]
So it has flipped and now the local one fails. Great
